name: Rspec

on: [push]

jobs:
  rspec:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 3
        uses: actions/setup-ruby@v1
      - name: Build
        env:
          RAILS_ENV: test
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run tests
        env:
          RAILS_ENV: test
        run: |
          bundle exec rspec